# EE3326 Numerical and Scientific Data Analysis Using Python

## Final Exam 

#### Name: Jeremy

#### LastName: Wolfson

#### Number: 42

* Python Multiple Choice (20 Points) - done
* Python Basics (20 Points) - done
* Numpy Basics (20 Points) - done
* Python Graphs (10 Points) - done
* Pandas Basics (10 Points) - done
* Python OOP Basics (20 Points) - IP
* Bonus (10 Points) - done

## Part I - Multiple Choice - 20 Points

Please opne ```Final_Exam_MC.pdf``` and use the form
https://forms.gle/CbmgtCPLDDQbb9i66

## Part II - Python Basics (Do not use Numpy/Scipy/Pandas) - 20 Points

You need to work on the basics of Python and standard libraries for this section of the exam. Please make sure to assign your code names similar functionality of your code as well as section numbers.

In [ ]:
# a) Using the random library, create a 4x4 matrix A, all elements are between -10 and 10
# 2 points



import random
W=[]
X=[]
Y=[]
Z=[]
n=4
for i in range(n):
    W.append(random.randint(-10,10))
    X.append(random.randint(-10,10))
    Y.append(random.randint(-10,10))
    Z.append(random.randint(-10,10))

A = [W, X, Y, Z]

# Print the matrix
for row in A:
    print(row)

In [ ]:
# b) Create  a 4x4 matrix B where all elements are 1
# 2 points



import random
WW=[]
XX=[]
YY=[]
ZZ=[]
n=4

for i in range(n):
    WW.append(1)
    XX.append(1)
    YY.append(1)
    ZZ.append(1)

B = [WW, XX, YY, ZZ]
for row in B:
    print(row)

In [ ]:
# c) Using the matrix A in part a, create an 1D array x that has all elements of A (Flatten 2D array to 1D)
# For example if you have A=[[1, 3, 1, 3],[4, 3, 7, 2],[9, 3, 3, 13],[11, 31, 21, 33]]
# result should be x=[1, 3, 1, 3, 4, 3, 7, 2, 9, 3, 3, 13, 11, 31, 21, 33]
# 2 points



x = []
for row in A:
    x.extend(row)
print(x)

In [ ]:
# d) Using the array x in part c, create an array y = x[2n]. 
# result should be y=[1, 1, 4, 7, 9, 3, 11, 21]
# 2 Points



y = x[::2]
print(y)

In [ ]:
# e) Using the array y in part d, create an array z = y[n/3]. 
# result should be y=[1,0,0, 1,0,0, 4, 0,0,7,0,0, 9,0,0, 3,0,0, 11,0,0, 21,0,0]
# 2 Points



n = 4
z = []
for i in y:
    z.append(i)
    z.extend([0, 0])
print(z)

In [ ]:
# f) write a program that extract even and odd numbers and quits if there is a negative number in a list
# 2 Points
num = [1, 3, 2, 1, 2, 3, -1, 0, 1, 3,19,20]
even=[]
odd=[]

# Your Code Goes here



def extractor (series): 
    for i in series: 
        if i < 0: 
            break
        elif i % 2 == 0: # even
            even.append(i)
        elif i % 2 == 1: # odd
            odd.append(i)
            
# Test your program 
extractor(num)

print(even) # should print [2, 2]
print(odd) # should print [1, 3, 1, 3]

In [ ]:
# g) Using the Matrix A in Part a, find the transpose of matrix A. 
# 4 Points



n = len(A)
A_transposed = [[0]* n for i in range(n)]

for i in range(n):
    for j in range(n):
        A_transposed[i][j] = A[j][i]

for row in A_transposed:
    print(row)

In [ ]:
# h) Using the Matrix A in Part a, find the C=AxA (A^2). 
# 4 Points



n = len(A)
C = [[0] * n for _ in range(n)]

for i in range(n):
    for j in range(n):
        buffer = 0
        for k in range(n):
            buffer += A[i][k] * A[k][j]
        C[i][j] = buffer
            
#for row in A:
#    print(row)

for row in C:
    print(row)

## Part III - Numpy - 20 Points

In [ ]:
# a) Write a NumPy program to convert a list of numeric values into a two-dimensional NumPy array (call it X) (make it 3x3)
# 2 point



import numpy as np

a=np.arange(9).reshape(3,3)
print(a)

In [ ]:
# b) Using the matrix X in part a and Transpose of X,  perform 
# # # element-by-element product
# # # matrix multiplication 
# 2 point



import numpy as np

for row in A:
    print(row)
print( )
        
for row in A_transposed: 
    print(row)
    
print( )

A = np.array(A)
A_transposed = np.array(A_transposed)

multiplication_matrix = A * A_transposed
for row in multiplication_matrix:
    print(row)

In [ ]:
# c) Write a NumPy program to create a 12x12 matrix, in which the elements on the borders will be equal to 1, and inside 0.
# 2 point



import numpy as np
def zeros_creator(): 
    the_matrix = np.zeros((12,12), dtype = int)
    return the_matrix
the_matrix = zeros_creator()
the_matrix[0,:] = 1
the_matrix[-1,:] = 1
the_matrix[:,0] = 1
the_matrix[:,-1] = 1
print(the_matrix)

In [ ]:
# d) Write a NumPy program to find common values between two arrays.
# 2 point



import numpy as np
ex_1 = np.array([6,7])
ex_2 = np.array([7,8,9])


def array_comparer(a,b): 
    print(np.intersect1d(a, b))

array_comparer(ex_1,ex_2)

In [ ]:
# e) Write a NumPy program to create a 5x5 identity matrix with diagonal elements are 1, the rest are 0.
# 1 point



import numpy as np
def diag_creator(): 
    return np.diag(np.array([1,1,1,1,1]))

diag_creator()

In [ ]:
# f) Write a NumPy program to find the union of two arrays. Union returns the unique, sorted array of values that appear in either of the two input arrays.
# 1 point

# a.union(b) for dictionaries, not arrays



aa=np.arange(5)
bb=np.arange(25,35)

def unification_of_the_world (a,b): 
    
    return np.union1d(a,b)

unification_of_the_world(aa,bb)

In [ ]:
# g) Write a NumPy program to create an array of 4,5 shape and swap column 1 with column 4.
# 2 points



def array_colum_swapper(): 
    XXX = np.arange(20).reshape(4, 5)
    print(XXX)
    XXX[:, [0, 3]] = XXX[:, [3, 0]]
    print(XXX)

array_colum_swapper()

In [ ]:
# h) Write a NumPy program to create two arrays of integers from 20 to 80 for odd and even numbers.
# 3 Points



def master_creator(): 
    def creator_of_things():
        evenn = np.arange(20, 82, 2)
        oddd = np.arange(21, 80, 2)
        return evenn, oddd
    evenn, oddd = creator_of_things()
    print(evenn, oddd)

master_creator()

In [ ]:
# i) Write a NumPy program to save matrix X in part (a) as a csv file (numpy.csv)
# 2 Points



print(x)

def csv_creator(): 
    xxxx = np.savetxt("numpy.csv", x, delimiter=",")
    
csv_creator()

In [ ]:
# j) Write a NumPy program that opens the numpy.csv file and multiply by itself (dot product) and save it as product.csv
# 3 Points



def numpy_csv_multiplier(): 
    def reader(): 
        my_read = np.loadtxt('numpy.csv',delimiter=',')
        return my_read
    my_data = reader()
    l = [i**2 for i in my_data.flatten()]
    squared_array = np.array(l).reshape(my_data.shape)
    np.savetxt("product.csv", squared_array, delimiter=",", fmt="%d")

numpy_csv_multiplier()

## Part IV - Python Plotting Basics - 10 Points

In [ ]:
print(range)

In [ ]:
# a) plot f(x) = sin(x)cos(x^2) 
    # subplots that 1x2, 2x2, 4x4 plots with same plots.
    # make sure all have title, grid on, x-axis and y-axis labels
# 4 Points



import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0,6.28,80)
y = np.sin(x)*np.cos(x**2)
for i in range (1,3): 
    plt.subplot(1,2,i)
    plt.title(f'subplot (1,2,{i})')
    plt.plot(x,y)
    plt.xlabel("unit circle")
    plt.ylabel("unit vector maximum")
    plt.grid()
plt.tight_layout()
plt.show()

for i in range(1,5): 
    plt.subplot(2,2,i)
    plt.title(f'subplot (2,2,{i})')
    plt.xlabel("unit circle")
    plt.ylabel("unit vector maximum")
    plt.plot(x,y)
    plt.grid()
plt.tight_layout()
plt.show()


plt.figure(figsize=(12,12))
for i in range(1,17):
    plt.subplot(4,4,i)
    plt.plot(x, y, color="purple")
    plt.title(f'subplot (4,4,{i})')
    plt.xlabel("unit circle")
    plt.ylabel("unit vector maximum")
    plt.grid(True)

plt.tight_layout()
plt.show()

In [ ]:
# b) Create a plot that shows sin(x), cos(x^2) and sin(x^2)cos(x^2) on same plot. 
# 2 Points



import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0,6.28,8000000)
y1 = np.sin(x)
y2 = np.cos(x**2)
y3 = np.sin(x**2)*np.cos(x**2)
plt.subplot(3,1,1)
plt.plot(x,y1)
plt.subplot(3,1,2)
plt.plot(x,y2)
plt.subplot(3,1,3)
plt.plot(x,y3)
plt.tight_layout()
plt.show()

In [ ]:
# c) Save figures with different file types (png, svg, jpeg, pdf) and compare them based on file size and scalability.
# 2 Points



import matplotlib.pyplot as plt
import numpy as np

x=np.linspace(0,6.28,800000)
y1 = np.sin(x)
y2 = np.cos(x**2)
y3 = np.sin(x**2)*np.cos(x**2)
plt.subplot(3,1,1)
plt.plot(x,y1)
plt.savefig("sin_x.png")
plt.savefig("sin_x.svg")
plt.savefig("sin_x.pdf")
plt.show() # intentionally splitting each graph from being reitterated on
plt.subplot(3,1,2)
plt.plot(x,y2)
plt.savefig("cos_x_squared.png")
plt.savefig("cos_x_squared.svg")
plt.savefig("cos_x_squared.pdf")
plt.show()
plt.subplot(3,1,3)
plt.plot(x,y3)
plt.savefig("sin_x_cos_x.png")
plt.savefig("sin_x_cos_x.svg")
plt.savefig("sin_x_cos_x.pdf")
plt.show()

In [ ]:
# d) Create a 100x100 sparse matrix A and visualize it. 
# 2 Points



import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import random

matrix_reloaded = random(100, 100, density=0.05)
plt.spy(matrix_reloaded, markersize=2)
plt.grid()
plt.show()

## Part V - Pandas Basics - 10 Points

In [1]:
# a) Write a Python program to create and display a one-dimensional array-like object containing an array of data using the Pandas module.
# 1 Point



import pandas as pd
project_grades = [100,38,96,90,0]
seriess=pd.Series(project_grades)
print(seriess)

0    100
1     38
2     96
3     90
4      0
dtype: int64

In [2]:
# b) Write a Python program to convert a dictionary to a Pandas series. Give an example
# 2 Point



import pandas as pd
project_grades = {
    "Project 1": 100,
    "Project 2": 38,
    "Project 3": 96,
    "Project 4": 90,
    "Project 5": 0
}
seriess = pd.Series(project_grades)
print(f'My project grades are {seriess}')

My project grades are Project 1    100
Project 2     38
Project 3     96
Project 4     90
Project 5      0
dtype: int64

In [3]:
# c) Create a DataFrame of Data below.
# 1 Points



import pandas as pd

Data = [(11, 'Christine', 'Swackhammer', 'ajb47@txstate.edu', 'A87427287', 81),
 (1, 'Robert', 'Clark', 'ztf38@txstate.edu', 'A66481744', 82),
 (19, 'Carol', 'Mcbride', 'pho11@txstate.edu', 'A76537425', 82),
 (7, 'Jamie', 'Yu', 'gey15@txstate.edu', 'A85320016', 83),
 (20, 'Brandon', 'Zeiner', 'gfs79@txstate.edu', 'A07737597', 83),
 (9, 'Alberto', 'Brogan', 'ghb24@txstate.edu', 'A33995337', 85),
 (10, 'Marguerite', 'Murphy', 'vyl68@txstate.edu', 'A73211898', 85),
 (3, 'Teresa', 'Flynn', 'mxw79@txstate.edu', 'A28987879', 86),
 (18, 'Florence', 'Whitesides', 'fju27@txstate.edu', 'A88567952', 86),
 (22, 'Jeffrey', 'Wester', 'cna97@txstate.edu', 'A69862678', 86),
 (31, 'Dawn', 'Rucker', 'cxl49@txstate.edu', 'A79280316', 86),
 (42, 'James', 'Pinales', 'lnb29@txstate.edu', 'A09974477', 88),
 (26, 'Barbara', 'Brady', 'moq00@txstate.edu', 'A65375783', 90),
 (5, 'Hilda', 'Spivey', 'kpy39@txstate.edu', 'A37354216', 91),
 (24, 'Stacey', 'Hernandez', 'lcc98@txstate.edu', 'A68967147', 93),
 (29, 'Antoinette', 'Smith', 'ybx60@txstate.edu', 'A30958002', 93),
 (48, 'Charles', 'Small', 'myo05@txstate.edu', 'A48344838', 94),
 (50, 'Theresa', 'Kern', 'zra61@txstate.edu', 'A23010111', 94),
 (17, 'William', 'Jensen', 'kgq55@txstate.edu', 'A20371305', 96),
 (28, 'Susan', 'Robinson', 'ihs79@txstate.edu', 'A81841801', 97),
 (4, 'Mary', 'Menist', 'ghf58@txstate.edu', 'A83696382', 100)]

df = pd.DataFrame(Data, columns=["Student Class Number", "Fname", "Lname", "Email", "Student ID", "Final Grade"])
print(df)
df

    Student Class Number       Fname        Lname              Email  \
0                     11   Christine  Swackhammer  ajb47@txstate.edu
1                      1      Robert        Clark  ztf38@txstate.edu
2                     19       Carol      Mcbride  pho11@txstate.edu
3                      7       Jamie           Yu  gey15@txstate.edu
4                     20     Brandon       Zeiner  gfs79@txstate.edu
5                      9     Alberto       Brogan  ghb24@txstate.edu
6                     10  Marguerite       Murphy  vyl68@txstate.edu
7                      3      Teresa        Flynn  mxw79@txstate.edu
8                     18    Florence   Whitesides  fju27@txstate.edu
9                     22     Jeffrey       Wester  cna97@txstate.edu
10                    31        Dawn       Rucker  cxl49@txstate.edu
11                    42       James      Pinales  lnb29@txstate.edu
12                    26     Barbara        Brady  moq00@txstate.edu
13                     5       Hilda       Spivey  kpy39@txstate.edu
14                    24      Stacey    Hernandez  lcc98@txstate.edu
15                    29  Antoinette        Smith  ybx60@txstate.edu
16                    48     Charles        Small  myo05@txstate.edu
17                    50     Theresa         Kern  zra61@txstate.edu
18                    17     William       Jensen  kgq55@txstate.edu
19                    28       Susan     Robinson  ihs79@txstate.edu
20                     4        Mary       Menist  ghf58@txstate.edu

   Student ID  Final Grade
0   A87427287           81
1   A66481744           82
2   A76537425           82
3   A85320016           83
4   A07737597           83
5   A33995337           85
6   A73211898           85
7   A28987879           86
8   A88567952           86
9   A69862678           86
10  A79280316           86
11  A09974477           88
12  A65375783           90
13  A37354216           91
14  A68967147           93
15  A30958002           93
16  A48344838           94
17  A23010111           94
18  A20371305           96
19  A81841801           97
20  A83696382          100

,Student Class Number,Fname,Lname,Email,Student ID,Final Grade
0,11,Christine,Swackhammer,ajb47@txstate.edu,A87427287,81
1,1,Robert,Clark,ztf38@txstate.edu,A66481744,82
2,19,Carol,Mcbride,pho11@txstate.edu,A76537425,82
3,7,Jamie,Yu,gey15@txstate.edu,A85320016,83
4,20,Brandon,Zeiner,gfs79@txstate.edu,A07737597,83
5,9,Alberto,Brogan,ghb24@txstate.edu,A33995337,85
6,10,Marguerite,Murphy,vyl68@txstate.edu,A73211898,85
7,3,Teresa,Flynn,mxw79@txstate.edu,A28987879,86
8,18,Florence,Whitesides,fju27@txstate.edu,A88567952,86
9,22,Jeffrey,Wester,cna97@txstate.edu,A69862678,86
10,31,Dawn,Rucker,cxl49@txstate.edu,A79280316,86
11,42,James,Pinales,lnb29@txstate.edu,A09974477,88
12,26,Barbara,Brady,moq00@txstate.edu,A65375783,90
13,5,Hilda,Spivey,kpy39@txstate.edu,A37354216,91
14,24,Stacey,Hernandez,lcc98@txstate.edu,A68967147,93
15,29,Antoinette,Smith,ybx60@txstate.edu,A30958002,93
16,48,Charles,Small,myo05@txstate.edu,A48344838,94
17,50,Theresa,Kern,zra61@txstate.edu,A23010111,94
18,17,William,Jensen,kgq55@txstate.edu,A20371305,96
19,28,Susan,Robinson,ihs79@txstate.edu,A81841801,97
20,4,Mary,Menist,ghf58@txstate.edu,A83696382,100

In [11]:
# d) Write a Pandas program to get the first and last 3 rows of a given DataFrame.
# 2 Point



def top_n_bottom(): 
    my_top_3 = df.head(3)
    my_bottom_3 = df.tail(3)
    return my_top_3,my_bottom_3
    
my_top_3, my_bottom_3 = top_n_bottom()

print(f'My top 3 are {my_top_3}, and bottom 3 are {my_bottom_3}')

My top 3 are    Student Class Number      Fname        Lname              Email Student ID  \
0                    11  Christine  Swackhammer  ajb47@txstate.edu  A87427287
1                     1     Robert        Clark  ztf38@txstate.edu  A66481744
2                    19      Carol      Mcbride  pho11@txstate.edu  A76537425

   Final Grade
0           81
1           82
2           82  , and bottom 3 are     Student Class Number    Fname     Lname              Email Student ID  \
18                    17  William    Jensen  kgq55@txstate.edu  A20371305
19                    28    Susan  Robinson  ihs79@txstate.edu  A81841801
20                     4     Mary    Menist  ghf58@txstate.edu  A83696382

    Final Grade
18           96
19           97
20          100

In [12]:
# e) Convert the DataFrame in part c in to a dictionary 
# 1 Point



import pandas as pd
df_to_dictionary = df.to_dict(orient="dict")
print(df_to_dictionary)
df_to_dictionary

{'Student Class Number': {0: 11, 1: 1, 2: 19, 3: 7, 4: 20, 5: 9, 6: 10, 7: 3, 8: 18, 9: 22, 10: 31, 11: 42, 12: 26, 13: 5, 14: 24, 15: 29, 16: 48, 17: 50, 18: 17, 19: 28, 20: 4}, 'Fname': {0: 'Christine', 1: 'Robert', 2: 'Carol', 3: 'Jamie', 4: 'Brandon', 5: 'Alberto', 6: 'Marguerite', 7: 'Teresa', 8: 'Florence', 9: 'Jeffrey', 10: 'Dawn', 11: 'James', 12: 'Barbara', 13: 'Hilda', 14: 'Stacey', 15: 'Antoinette', 16: 'Charles', 17: 'Theresa', 18: 'William', 19: 'Susan', 20: 'Mary'}, 'Lname': {0: 'Swackhammer', 1: 'Clark', 2: 'Mcbride', 3: 'Yu', 4: 'Zeiner', 5: 'Brogan', 6: 'Murphy', 7: 'Flynn', 8: 'Whitesides', 9: 'Wester', 10: 'Rucker', 11: 'Pinales', 12: 'Brady', 13: 'Spivey', 14: 'Hernandez', 15: 'Smith', 16: 'Small', 17: 'Kern', 18: 'Jensen', 19: 'Robinson', 20: 'Menist'}, 'Email': {0: 'ajb47@txstate.edu', 1: 'ztf38@txstate.edu', 2: 'pho11@txstate.edu', 3: 'gey15@txstate.edu', 4: 'gfs79@txstate.edu', 5: 'ghb24@txstate.edu', 6: 'vyl68@txstate.edu', 7: 'mxw79@txstate.edu', 8: 'fju27@txstate.edu', 9: 'cna97@txstate.edu', 10: 'cxl49@txstate.edu', 11: 'lnb29@txstate.edu', 12: 'moq00@txstate.edu', 13: 'kpy39@txstate.edu', 14: 'lcc98@txstate.edu', 15: 'ybx60@txstate.edu', 16: 'myo05@txstate.edu', 17: 'zra61@txstate.edu', 18: 'kgq55@txstate.edu', 19: 'ihs79@txstate.edu', 20: 'ghf58@txstate.edu'}, 'Student ID': {0: 'A87427287', 1: 'A66481744', 2: 'A76537425', 3: 'A85320016', 4: 'A07737597', 5: 'A33995337', 6: 'A73211898', 7: 'A28987879', 8: 'A88567952', 9: 'A69862678', 10: 'A79280316', 11: 'A09974477', 12: 'A65375783', 13: 'A37354216', 14: 'A68967147', 15: 'A30958002', 16: 'A48344838', 17: 'A23010111', 18: 'A20371305', 19: 'A81841801', 20: 'A83696382'}, 'Final Grade': {0: 81, 1: 82, 2: 82, 3: 83, 4: 83, 5: 85, 6: 85, 7: 86, 8: 86, 9: 86, 10: 86, 11: 88, 12: 90, 13: 91, 14: 93, 15: 93, 16: 94, 17: 94, 18: 96, 19: 97, 20: 100}}

{'Student Class Number': {0: 11,
  1: 1,
  2: 19,
  3: 7,
  4: 20,
  5: 9,
  6: 10,
  7: 3,
  8: 18,
  9: 22,
  10: 31,
  11: 42,
  12: 26,
  13: 5,
  14: 24,
  15: 29,
  16: 48,
  17: 50,
  18: 17,
  19: 28,
  20: 4},
 'Fname': {0: 'Christine',
  1: 'Robert',
  2: 'Carol',
  3: 'Jamie',
  4: 'Brandon',
  5: 'Alberto',
  6: 'Marguerite',
  7: 'Teresa',
  8: 'Florence',
  9: 'Jeffrey',
  10: 'Dawn',
  11: 'James',
  12: 'Barbara',
  13: 'Hilda',
  14: 'Stacey',
  15: 'Antoinette',
  16: 'Charles',
  17: 'Theresa',
  18: 'William',
  19: 'Susan',
  20: 'Mary'},
 'Lname': {0: 'Swackhammer',
  1: 'Clark',
  2: 'Mcbride',
  3: 'Yu',
  4: 'Zeiner',
  5: 'Brogan',
  6: 'Murphy',
  7: 'Flynn',
  8: 'Whitesides',
  9: 'Wester',
  10: 'Rucker',
  11: 'Pinales',
  12: 'Brady',
  13: 'Spivey',
  14: 'Hernandez',
  15: 'Smith',
  16: 'Small',
  17: 'Kern',
  18: 'Jensen',
  19: 'Robinson',
  20: 'Menist'},
 'Email': {0: 'ajb47@txstate.edu',
  1: 'ztf38@txstate.edu',
  2: 'pho11@txstate.edu',
  3: 'gey15@txstate.edu',
  4: 'gfs79@txstate.edu',
  5: 'ghb24@txstate.edu',
  6: 'vyl68@txstate.edu',
  7: 'mxw79@txstate.edu',
  8: 'fju27@txstate.edu',
  9: 'cna97@txstate.edu',
  10: 'cxl49@txstate.edu',
  11: 'lnb29@txstate.edu',
  12: 'moq00@txstate.edu',
  13: 'kpy39@txstate.edu',
  14: 'lcc98@txstate.edu',
  15: 'ybx60@txstate.edu',
  16: 'myo05@txstate.edu',
  17: 'zra61@txstate.edu',
  18: 'kgq55@txstate.edu',
  19: 'ihs79@txstate.edu',
  20: 'ghf58@txstate.edu'},
 'Student ID': {0: 'A87427287',
  1: 'A66481744',
  2: 'A76537425',
  3: 'A85320016',
  4: 'A07737597',
  5: 'A33995337',
  6: 'A73211898',
  7: 'A28987879',
  8: 'A88567952',
  9: 'A69862678',
  10: 'A79280316',
  11: 'A09974477',
  12: 'A65375783',
  13: 'A37354216',
  14: 'A68967147',
  15: 'A30958002',
  16: 'A48344838',
  17: 'A23010111',
  18: 'A20371305',
  19: 'A81841801',
  20: 'A83696382'},
 'Final Grade': {0: 81,
  1: 82,
  2: 82,
  3: 83,
  4: 83,
  5: 85,
  6: 85,
  7: 86,
  8: 86,
  9: 86,
  10: 86,
  11: 88,
  12: 90,
  13: 91,
  14: 93,
  15: 93,
  16: 94,
  17: 94,
  18: 96,
  19: 97,
  20: 100}}

In [13]:
# f) Save the DataFrame as a CSV file
# 1 Point



df.to_csv("data.csv")

In [14]:
# g) Save the DataFrame as an excel file
# 1 Point



df.to_excel("excel.xlsx")

In [15]:
# h) Using the Data in Part c, create a dataframe without Email addresses 
# 1 Point



if "Email" in df.columns: 
    df = df.drop("Email", axis=1)
df

    Student Class Number       Fname        Lname Student ID  Final Grade
0                     11   Christine  Swackhammer  A87427287           81
1                      1      Robert        Clark  A66481744           82
2                     19       Carol      Mcbride  A76537425           82
3                      7       Jamie           Yu  A85320016           83
4                     20     Brandon       Zeiner  A07737597           83
5                      9     Alberto       Brogan  A33995337           85
6                     10  Marguerite       Murphy  A73211898           85
7                      3      Teresa        Flynn  A28987879           86
8                     18    Florence   Whitesides  A88567952           86
9                     22     Jeffrey       Wester  A69862678           86
10                    31        Dawn       Rucker  A79280316           86
11                    42       James      Pinales  A09974477           88
12                    26     Barbara        Brady  A65375783           90
13                     5       Hilda       Spivey  A37354216           91
14                    24      Stacey    Hernandez  A68967147           93
15                    29  Antoinette        Smith  A30958002           93
16                    48     Charles        Small  A48344838           94
17                    50     Theresa         Kern  A23010111           94
18                    17     William       Jensen  A20371305           96
19                    28       Susan     Robinson  A81841801           97
20                     4        Mary       Menist  A83696382          100

## Part VI - Python OOP Basics - 20 Points

a) Create a Employee Class with

b) Create two class variables

c) Create **Instance Methods**

d) Create **Class** and **Static**  Methods   

e) Create **Magic Methods**  Methods

In [1]:
#Create a Employee Class
'''
def __init__(self, fname, lname, ID, pay, vac_days):
'''



def __init__(self, fname, lname, ID, pay, vac_days):
        self.fname = fname
        self.lname = lname
        self.ID = ID
        self.pay = pay
        self.vac_days = vac_days

In [2]:
#b) Create two class variables
'''
i. **ANNUAL_BONUS_RATE**: This should be applied to the 'Pay' when eligible. It should be 10%
    ANNUAL_BONUS_RATE = 0.10  # 10%
    
ii. **total_employees**: Class variable to keep track of the total number of employees created. Initial value should be zero.
'''



class Employee: 
    ANNUAL_BONUS_RATE = 0.1
    total_employees = 0
    def __init__(self, fname, lname, ID, pay, vac_days):
        self.fname = fname
        self.lname = lname
        self.ID = ID
        self.pay = pay
        self.vac_days = vac_days
        Employee.total_employees += 1

In [3]:
#c) Create **Instance Methods**



    def email_address(self):
        """Creates and returns the professional email address (FirstInitial_LastName@cool.com)."""
        first_initial = self.fname[0].lower()
        last_name = self.lname.lower()
        return f"{first_initial}{last_name}@cool.com"

    def calculate_bonus(self):
        """Calculates a bonus based on vacation days and the class bonus rate."""
        if self.vac_days >= 10:
            bonus = self.pay * Employee.ANNUAL_BONUS_RATE
            return bonus
        else:
            return 0

    def reset_vacation_days(self):
        """Resets the employee's vac_days to zero."""
        self.vac_days = 0

    def apply_raise(self, percentage):
        """Increases the employee's pay by a given percentage."""
        if percentage > 0:
            self.pay += self.pay * (percentage / 100)

IndentationError: unexpected indent (811324234.py, line 5)

In [4]:
#d) Create **Class** and **Static**  Methods



    @classmethod
    def set_bonus_rate(cls, new_rate):
        """Updates the ANNUAL_BONUS_RATE class variable for all employees."""
        cls.ANNUAL_BONUS_RATE = new_rate
    
    @staticmethod
    def is_workday(day):
        """Checks if a given day is a standard workday (not Saturday or Sunday)."""
        return day.weekday() < 5

    @staticmethod
    def format_id(employee_id):
        """Formats the ID as a 4-digit string with leading zeros."""
        return f"{employee_id:04d}"

IndentationError: unexpected indent (2009620744.py, line 5)

In [5]:
#e) Create **Magic Methods**  Methods



    def __repr__(self):
        """The 'official' string representation, primarily for debugging."""
        return (f"Employee(ID='{self.ID}', name='{self.fname} {self.lname}', "
        f"pay={self.pay}, vac_days={self.vac_days})")

    def __add__(self, other):
        """Defines the behavior of the '+' operator: adds the pay of two employees."""
        if isinstance(other, Employee):
            return self.pay + other.pay
        return NotImplemented

IndentationError: unexpected indent (443474795.py, line 5)

 # Combined

In [6]:
'''def __init__(self, fname, lname, ID, pay, vac_days):
        self.fname = fname
        self.lname = lname
        self.ID = ID
        self.pay = pay
        self.vac_days = vac_days'''

class Employee: 
    ANNUAL_BONUS_RATE = 0.1
    total_employees = 0
    def __init__(self, fname, lname, ID, pay, vac_days):
        self.fname = fname
        self.lname = lname
        self.ID = ID
        self.pay = pay
        self.vac_days = vac_days
        Employee.total_employees += 1

    def email_address(self):
        """Creates and returns the professional email address (FirstInitial_LastName@cool.com)."""
        first_initial = self.fname[0].lower()
        last_name = self.lname.lower()
        return f"{first_initial}{last_name}@cool.com"

    def calculate_bonus(self):
        """Calculates a bonus based on vacation days and the class bonus rate."""
        if self.vac_days >= 10:
            bonus = self.pay * Employee.ANNUAL_BONUS_RATE
            return bonus
        else:
            return 0

    def reset_vacation_days(self):
        """Resets the employee's vac_days to zero."""
        self.vac_days = 0

    def apply_raise(self, percentage):
        """Increases the employee's pay by a given percentage."""
        if percentage > 0:
            self.pay += self.pay * (percentage / 100)

    @classmethod
    def set_bonus_rate(cls, new_rate):
        """Updates the ANNUAL_BONUS_RATE class variable for all employees."""
        cls.ANNUAL_BONUS_RATE = new_rate
    
    @staticmethod
    def is_workday(day):
        """Checks if a given day is a standard workday (not Saturday or Sunday)."""
        return day.weekday() < 5

    @staticmethod
    def format_id(employee_id):
        """Formats the ID as a 4-digit string with leading zeros."""
        return f"{employee_id:04d}"

    def __repr__(self):
        """The 'official' string representation, primarily for debugging."""
        return (f"Employee(ID='{self.ID}', name='{self.fname} {self.lname}', "
        f"pay={self.pay}, vac_days={self.vac_days})")

    def __add__(self, other):
        """Defines the behavior of the '+' operator: adds the pay of two employees."""
        if isinstance(other, Employee):
            return self.pay + other.pay
        return NotImplemented

## Part VII - Bonus - 10 Points



Using the figure below Calculate the $\int_{0}^{1}\sqrt{x}$

* By hand using your calculus knowledge or use online tools if you wanr like https://www.wolframalpha.com/calculators/integral-calculator/
* Using the Orange Interpretations
* Using the green Interpretations


<img src="Integral_approximations.png" alt="Drawing" style="width: 600px;"/>
<center>Figure 3. Problem 5 </center>